title: Jared S (BigxMac)
description: {A blog about a programmer}

url:
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html

social:
   github: BigxMac
